name: Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21.2.0"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run build to generate the dist folder
      - name: Build project
        run: npm run build

      # Upload the dist folder as an artifact after the build
      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
